static const AVCodec * const codec_list[] = {
    &ff_gif_encoder,
    &ff_mjpeg_encoder,
    &ff_png_encoder,
    &ff_aac_encoder,
    &ff_libx264_encoder,
    &ff_gif_decoder,
    &ff_h263_decoder,
    &ff_h264_decoder,
    &ff_h264_mediacodec_decoder,
    &ff_mjpeg_decoder,
    &ff_mpeg4_decoder,
    &ff_png_decoder,
    &ff_aac_decoder,
    &ff_mp3_decoder,
    &ff_hevc_mediacodec_decoder,
    &ff_mpeg4_mediacodec_decoder,
    &ff_vp8_mediacodec_decoder,
    &ff_vp9_mediacodec_decoder,
    NULL };
